name: Publish
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Build
      run: 
        npm install
        npm run build
    - name: Zip
      run: 
        npm install npm-build-zip
        npm run zip
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@v4.0.1
      with:
        file-path: dist/chrome-extension-boilerplate-react_4.4.0.zip
        extension-id: aoddfhmgjbfabdnjeddaodkcglgabkoa
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}